### ISSUE TITLE
[Question] Update

### ISSUE THREAD

**Issue by wasyady** [RumbleFrog/Anti-Private#10]
Can you update this plugin?
 [https://steamcommunity.com/games/593110/announcements/detail/1667896941884942467](https://steamcommunity.com/games/593110/announcements/detail/1667896941884942467)

**Comment by rumblefrog** [comment]
Did that update break this plugin or something?

**Comment by wasyady** [comment]
Yeah, Players can set games, for friend, or private.

**Comment by rumblefrog** [comment]
Yeah, I know that, but does it affect the API? I currently don't have a server to test this on

**Comment by wasyady** [comment]
I think, I can help for you. 
http://steamcommunity.com/id/wacci/

**Comment by rumblefrog** [comment]
There's nothing changed in the API, plus there isn't a new revision of the API resource, so the plugin should be working as intended still.

**Comment by rumblefrog** [comment]
Test it and lmk if it doesn't work
