### ISSUE TITLE
[FeatureRequest] CS:GO inventory check.

### ISSUE THREAD

**Issue by BattlefieldTsk** [RumbleFrog/Anti-Private#11]
1. **Private inventory:**

`curl https://steamcommunity.com/profiles/76561198157196XXX/inventory/json/730/2`

>  {"success":false,"Error":"This profile is private."}

2. **Public inventory:**

`curl https://steamcommunity.com/profiles/76561198008900XXX/inventory/json/730/2`

> {"success":true,"rgInventory":{"14581506282":etc

3. **After 3-d request per minute for the same URL:**

header is
`curl -I https://steamcommunity.com/profiles/76561198157196XXX/inventory/json/730/2`

> HTTP/1.1 429 Too Many Requests

or body is
`$ curl https://steamcommunity.com/profiles/76561198157196XXX/inventory/json/730/2`

> null

**Comment by rumblefrog** [comment]
So what's the feature request? Or is this a bug fix request.

**Comment by BattlefieldTsk** [comment]
This not a bug report. This is request of new feature (functional).
Now after run CS:GO server with this plugin i received message "This game does not support private inventory check". (https://github.com/rumblefrog/Anti-Private/blob/master/Anti_Private.sp#L87) This is normal behavior, because CS:GO is not supported now.

Add the ability to check opened or closed CS:GO inventory for all using the report above.

**Comment by kjsmita6** [comment]
Fixed by #17 ~~, although you would need to edit `InventoryURL` to be `https://steamcommunity.com/inventory/%s/730/2?l=english&count=1` and recompile.~~

Edit: No need to change the inventory URL since players can't make their inventory private for one game and public for another, so the TF2 url would work for CSGO and any other game.

**Comment by rumblefrog** [comment]
Fixed by #17
