### ISSUE TITLE
Game Hours privacy settings

### ISSUE THREAD

**Issue by alphaearth** [RumbleFrog/Anti-Private#12]
From the privacy settings, the player who hides the game clock is not throwing away from the server. Can you fix the error?

**Comment by rumblefrog** [comment]
What you mean the game clock

**Comment by alphaearth** [comment]
I mean played game hours.

**Comment by rumblefrog** [comment]
I don't think that's part of this plugin, this plugin checks for inventory privacy, whether or not the gameplay hours is public, it's not accounted for.

**Comment by alphaearth** [comment]
Can you set all profile privacy settings to be turned on? I can't control the game hours of the players.
One missing: Doesn't check whether the game hours is on or off.
