### ISSUE TITLE
Game hours check

### ISSUE THREAD

**Issue by lazhoroni** [RumbleFrog/Anti-Private#13]
http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key={key}&appids_filter[0]={game}&steamid={steamid}&format=json

http://api.steampowered.com/ISteamUser/GetFriendList/v0001/?key={key}&steamid={steamid}&relationship=friend&format=json

can you have the player's game hours checked using this link? get the setting for the player's hours. Sample; If the player has less than 200 hours of game time, he / she cannot login to the server.

**Comment by rumblefrog** [comment]
Out of scope of the project.

Anti **private**
