### ISSUE TITLE
Supported games ?

### ISSUE THREAD

**Issue by wasyady** [RumbleFrog/Anti-Private#2]
This is a really great idea! Hope it will work really well! :thumbsup:

What games will you support? :blush:

**Comment by rumblefrog** [comment]
Currently, it'll support API call for TF2, Dota 2, and Portal 2.

Currently looking for an API that supports CSGO, since it has been permanently disabled by Valve.

**Comment by wasyady** [comment]
Have you seen this :
https://forums.alliedmods.net/showthread.php?t=299120

**Comment by rumblefrog** [comment]
I just took a look; it relies on an API server that the plugin author is hosting, which is a liability if he no longer wants to maintain it or it goes down.

**Comment by wasyady** [comment]
Yes and unfortunately not stable, so I do not use it.
I would like to use your plugin on CSGO.

v0.0.1 supporting CS:GO ? Or try it ? 😊

One more thing!
Can you prepare a detailed description of the installation?
Thanks in advance!

**Comment by rumblefrog** [comment]
v0.0.1 Does not support CSGO, but I just pushed another commit that's will allow CSGO to semi-work (you'll have to compile it), it'll check for private profile still, but cannot check for private inventory.

Yeah, I'll prepare a detailed description of the installation, I have to finish testing first.

**Comment by wasyady** [comment]
It's working with CS:Go too? 😊

**Comment by rumblefrog** [comment]
The only part non-functional is inventory checking, in which I'm unable to find a good replacement

**Comment by wasyady** [comment]
Thanks for work! :heart_eyes:
I will test it! :bowtie:
